name: Release-pipeline

on:
  push:
    tags:
      - '*'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Branch
        id: branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo "::set-output name=BRANCH_NAME::${branch}"
      - run: echo "The selected color is ${{ steps.branch.BRANCH_NAME }}"
      - name: print env
        run: printenv
      - name: Setup Go for Building
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.7'
      - name: Build carrier
        run: make build-all
        if: steps.branch.outputs.BRANCH_NAME == 'main'
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: ./cli/dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
