name: Release-pipeline

on:
  push:
    tags:
      - '*'
        
jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go for Building
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.7'
      - name: Build carrier
        run: make build-all
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: ./cli/dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
