name: Release-pipeline

on:
  push:
    tags:
      - '*'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch Branch
        id: branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "::set-output name=BRANCH_NAME::$branch"
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.7'
      - name: Build Carrier
        if: steps.branch.outputs.BRANCH_NAME == 'main'
        run: |
          make build-all-small
          make compress
      - name: Release Carrier
        if: steps.branch.outputs.BRANCH_NAME == 'main'
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: ./cli/dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}